export class Environment {
  public static readonly ROOT_URL: string = 'DOCKER:PROTOCOL://DOCKER:MACHINE_DOMAIN';
  public static readonly FACTS_DASHBOARD_SERVER: string = 'DOCKER:FACTS_DASHBOARD_URL';
  public static readonly USER_MANAGER_SERVER: string = 'DOCKER:USER_MANAGER_URL';
  public static readonly CADT_SERVER: string = 'DOCKER:CADT_URL';
  public static readonly APPOINTMENT_CENTER_SERVER: string = 'DOCKER:APPOINTMENT_CENTER_URL';
  public static readonly BOARDING_PASS_SERVER: string = 'DOCKER:BOARDING_PASS_URL';
  public static readonly XFORMS_SERVER: string = 'DOCKER:XFORMS_URL';
  public static readonly PROFILE_FORM_URL: string = 'DOCKER:PROFILE_FORM_URL';
  public static readonly SURVEYS_CREDIBILITY_SERVER: string = 'DOCKER:SURVEYS_CREDIBILITY_URL';
  public static readonly SURVEYS_NCA_SERVER: string = 'DOCKER:SURVEYS_NCA_URL';
  public static readonly PROFILE_MATCHER_SERVER: string = 'DOCKER:PROFILE_MATCHER_URL';
  public static readonly KNOWLEDGE_SYSTEM_SERVER: string = 'DOCKER:KNOWLEDGE_SYSTEM_URL';

  public static readonly CADT_GALLERY_CARD_VISIBLE = 'DOCKER:ENABLE_CADT';
  public static readonly NCA_GALLERY_CARD_VISIBLE = 'DOCKER:ENABLE_NCA';
  public static readonly CREDIBILITY_GALLERY_CARD_VISIBLE = 'DOCKER:ENABLE_CREDIBILITY';
  public static readonly XFORMS_GALLERY_CARD_VISIBLE = 'DOCKER:ENABLE_XFORMS';
  public static readonly PROFILE_FORM_GALLERY_CARD_VISIBLE = 'DOCKER:ENABLE_PROFILE_FORM';
  public static readonly USER_MANAGER_GALLERY_CARD_VISIBLE = 'DOCKER:ENABLE_USER_MANAGER';
  public static readonly DASHBOARD_GALLERY_CARD_VISIBLE = 'DOCKER:ENABLE_DASHBOARD';
  public static readonly APPOINTMENT_CENTER_GALLERY_CARD_VISIBLE = 'DOCKER:ENABLE_APPOINTMENT_CENTER';
  public static readonly BOARDING_PASS_GALLERY_CARD_VISIBLE = 'DOCKER:ENABLE_BOARDING_PASS';
  public static readonly PROFILE_MATCHER_GALLERY_CARD_VISIBLE = 'DOCKER:ENABLE_PROFILE_MATCHER';
  public static readonly KNOWLEDGE_SYSTEM_GALLERY_CARD_VISIBLE = 'DOCKER:ENABLE_KNOWLEDGE_SYSTEM';
}
